version: 1.0.{build}
environment:
  nodejs_version: 6
install:
- ps: >-
    ps: Install-Product node $env:nodejs_version

    npm install
build:
  verbosity: minimal
test_script:
- ps: >-
    node --version

    npm --version

    npm test